"""create tickets table

Revision ID: 4a4555f01d5e
Revises: 4b69ad794b44
Create Date: 2026-07-08 19:42:25.660661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a4555f01d5e'
down_revision: Union[str, None] = '4b69ad794b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_sweeper_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_sweeper_id'], ['mailbox_sweepers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_message_id'), 'tickets', ['message_id'], unique=True)
    # NOTE: autogenerate also flagged celery_taskmeta/celery_tasksetmeta as "removed" —
    # those belong to Celery's own db+postgresql result backend, not our models.
    # Left untouched on purpose.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_message_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
