"""add last_synced_at to mailbox_sweepers

Revision ID: 50b0e4e93234
Revises: 4a4555f01d5e
Create Date: 2026-07-08 19:54:59.395217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b0e4e93234'
down_revision: Union[str, None] = '4a4555f01d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also flagged celery_taskmeta/celery_tasksetmeta as "removed" —
    # those belong to Celery's own db+postgresql result backend, not our models.
    # Left untouched on purpose.
    op.add_column('mailbox_sweepers', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox_sweepers', 'last_synced_at')
    # ### end Alembic commands ###
